### ISSUE TITLE
[feature request] is there any plan for cuda-lldb

### ISSUE THREAD

**Issue by unship** [NVIDIA/cuda-gdb#3]
[feature request] is there any plan for cuda-lldb, since lldb is next generation, high-performance debugger

**Comment by steveulrich403** [comment]
Thanks for this feature request.  As you may have noticed, NVIDIA has resumed using github.com to publish our CUDA GDB sources, which is why you're receiving this reply after such a long period of time.  As with all feature requests, we will certainly consider it, but unfortunately we can't discuss specific feature commitments on public forums.
